on:
  push:
    branches:
      - main
  pull_request:

name: Test build

jobs:
  test-build:
    name: Test build
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Build image
        uses: docker/build-push-action@v5
        with:
          push: false
          load: true
          tags: ${{ github.repository }}:${{ github.sha }}

      - name: Test run
        run: docker run --rm ${GITHUB_REPOSITORY}:${GITHUB_SHA} --help
